### ISSUE TITLE
Support multi replicas

### ISSUE THREAD

**Issue by Thearas** [meilisearch/meilisearch-kubernetes#111]
**Description**

Same as https://github.com/meilisearch/meilisearch-kubernetes/issues/25. Any update?
(I can't reopen it so I open a new one)

Can I just change pvc's `accessModes` to `ReadWriteMany` and `replicas` to 2?

**Comment by alallema** [comment]
Hi @Thearas,
Sorry, I reopened the other question and I will close this one to keep the history. Meilisearch doesn't handle high availability, and for the moment the team is not working on it anymore. My bad I should explain that in the main issue.
Using the ReadWriteMany mode for mounted volumes could work to have a backup instance running (needs to be tested) but the data consistency can’t be guaranteed because Meilisearch is not ready to handle several instances reading/writing simultaneously from the same DB.
