### ISSUE TITLE
Add GitHub releases to CI

### ISSUE THREAD

**Issue by eskombro** [meilisearch/meilisearch-kubernetes#37]

**Comment by curquiza** [comment]
Hello!

A release **drafter** is useful when the release creation is done via the GitHub interface: you accumulate PRs and then, when you want, you trigger the release creation. Currently, in this package, it looks like each PR = a new release because the version changes in the chart file.

We could create releases on GitHub too, but the draft is not necessary: instead, we should configure a bot/hook that automatically creates a GitHub release after each PR merge when the version changes in the chart file.

Is it ok for you or do I miss something?

**Comment by eskombro** [comment]
As for now, we are only handling Helm charts and manifests, so this seems ok to me. 

But depending on its evolution, the Helm chart version won't necessarily reflect meilisearch-kubernetes version in the future.

So maybe having GitHub releases make sense. As for now, we can totally automate them and make them correspond to the version we are defining on the charts, and if this evolves we can reconsider!

**Comment by eskombro** [comment]
I changed the title of this issue, feel free to modify if you want it to be more specific or reflect something different :)

**Comment by curquiza** [comment]
In the other SDKs, we automate in CIs:
- the update of the release draft when the PR is merged.
- the push of the package when a release is triggered. Ex: the JS SDK is built and then is pushed to npm...

Sorry for my noob question, but this repo does not seem to have any publishment of the package to any platform, am I right? And for the moment, there is no need for a release drafter since there is no real release process except "a new PR merged is a new release". So what does `Add GitHub releases to CI` mean? We need to decide the new way of releasing before automating anything in a CI. But maybe I missed a point...

The first step to avoiding confusion would have been to add a description to the issue 😉 But I don't recommend doing this now: this would add confusion and my answer is already weird since you renamed the issue.
Maybe open a new one with a minimal description about what you mean by "Add GitHub releases to CI" (a new release process?) would be a better idea 😄 

I like this kind of improvement anyway! This will make this package better for contribution!!
And sorry if I missed something and my message makes more confusion.

**Comment by eskombro** [comment]
Thanks @curquiza 

The Helm chart publish process to an "official" repository is discussed [here](https://github.com/meilisearch/meilisearch-kubernetes/issues/13) and no decision has been made, but is an interesting one. I think that this is the most important point to discuss now, and I realize I am kind of adding just unnecessary noise with this new issue, so I think the best option is to find a solution to that discussion, and then think about this.

> The first step to avoiding confusion would have been to add a description to the issue 😉 But I don't recommend doing this now.

100% agreed!

**Comment by curquiza** [comment]
Ah thanks, this was the kind of discussion I was looking for when writing my comment!!! 👍 Awesome!
