### ISSUE TITLE
meili-docs helm chart

### ISSUE THREAD

**Issue by renehernandez** [meilisearch/meilisearch-kubernetes#4]
I've thinking about the idea of having a ready-to-use helm chart that would do the following:

* Deploy the meilisearch chart
* Deploy the [docs-scraper](https://github.com/meilisearch/docs-scraper) as another component. Options could be:
    * Cronjob to run on a specific schedule, e.g daily, hourly
    * A listener pod that could wait for requests to trigger the docs-scraper cli
* A default frontend website that would have a search interface and links to each of the scraped endpoints

Any thoughts? Any other suggestions that could be added?

**Comment by eskombro** [comment]
It would be amazing! We can also use https://github.com/meilisearch/instant-meilisearch for the front-end!

**Comment by curquiza** [comment]
Seems like an idea of a complete project, not really related to meilisearch-kubernetes. This would involve a new integration.
Still a good idea anyway, but I close this one since it's not only related to this repo only. 
Feel free to open a detailed issue of your plan in [integration-guides](https://github.com/meilisearch/integration-guides) 🙂
